// @generated by protobuf-ts 2.6.0 with parameter optimize_code_size
// @generated from protobuf file "auth/auth.proto" (package "auth", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message auth.AuthenticateRequest
 */
export interface AuthenticateRequest {
    /**
     * @generated from protobuf field: string version = 2;
     */
    version: string; // Mostly for tracking client versions in the wild.
}
/**
 * @generated from protobuf message auth.AuthenticateResponse
 */
export interface AuthenticateResponse {
    /**
     * @generated from protobuf field: string access_token = 1;
     */
    accessToken: string;
    /**
     * @generated from protobuf field: string refresh_token = 2;
     */
    refreshToken: string;
}
/**
 * @generated from protobuf message auth.RefreshRequest
 */
export interface RefreshRequest {
    /**
     * @generated from protobuf field: string refresh_token = 1;
     */
    refreshToken: string;
}
/**
 * @generated from protobuf message auth.RefreshResponse
 */
export interface RefreshResponse {
    /**
     * @generated from protobuf field: string access_token = 1;
     */
    accessToken: string;
    /**
     * @generated from protobuf field: string refresh_token = 2;
     */
    refreshToken: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class AuthenticateRequest$Type extends MessageType<AuthenticateRequest> {
    constructor() {
        super("auth.AuthenticateRequest", [
            { no: 2, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.AuthenticateRequest
 */
export const AuthenticateRequest = new AuthenticateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuthenticateResponse$Type extends MessageType<AuthenticateResponse> {
    constructor() {
        super("auth.AuthenticateResponse", [
            { no: 1, name: "access_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "refresh_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.AuthenticateResponse
 */
export const AuthenticateResponse = new AuthenticateResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshRequest$Type extends MessageType<RefreshRequest> {
    constructor() {
        super("auth.RefreshRequest", [
            { no: 1, name: "refresh_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.RefreshRequest
 */
export const RefreshRequest = new RefreshRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshResponse$Type extends MessageType<RefreshResponse> {
    constructor() {
        super("auth.RefreshResponse", [
            { no: 1, name: "access_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "refresh_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message auth.RefreshResponse
 */
export const RefreshResponse = new RefreshResponse$Type();
/**
 * @generated ServiceType for protobuf service auth.Auth
 */
export const Auth = new ServiceType("auth.Auth", [
    { name: "Authenticate", options: {}, I: AuthenticateRequest, O: AuthenticateResponse },
    { name: "Refresh", options: {}, I: RefreshRequest, O: RefreshResponse }
]);
