// @generated by protobuf-ts 2.6.0 with parameter optimize_code_size
// @generated from protobuf file "shared/user.proto" (package "user", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message user.User
 */
export interface User {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string ory_id = 2;
     */
    oryId: string;
    /**
     * @generated from protobuf field: string first_name = 3;
     */
    firstName: string;
    /**
     * @generated from protobuf field: string last_name = 4;
     */
    lastName: string;
    /**
     * @generated from protobuf field: repeated user.User.VerifiableAddress addresses = 5;
     */
    addresses: User_VerifiableAddress[];
    /**
     * @generated from protobuf field: repeated user.User.VerifiableAddress recovery_addresses = 6;
     */
    recoveryAddresses: User_VerifiableAddress[];
    /**
     * @generated from protobuf field: string domain = 7;
     */
    domain: string;
    /**
     * @generated from protobuf field: string profile = 8;
     */
    profile: string;
}
/**
 * @generated from protobuf message user.User.VerifiableAddress
 */
export interface User_VerifiableAddress {
    /**
     * @generated from protobuf field: string address = 1;
     */
    address: string;
    /**
     * @generated from protobuf field: bool verified = 2;
     */
    verified: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class User$Type extends MessageType<User> {
    constructor() {
        super("user.User", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ory_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "first_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "last_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "addresses", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => User_VerifiableAddress },
            { no: 6, name: "recovery_addresses", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => User_VerifiableAddress },
            { no: 7, name: "domain", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "profile", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message user.User
 */
export const User = new User$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_VerifiableAddress$Type extends MessageType<User_VerifiableAddress> {
    constructor() {
        super("user.User.VerifiableAddress", [
            { no: 1, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "verified", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message user.User.VerifiableAddress
 */
export const User_VerifiableAddress = new User_VerifiableAddress$Type();
